import type { BookingFrequency, BookingProperty, PaymentOption } from "../bookings/types";

export type QuoteStatus="DRAFT"|"SENT"|"VIEWED"|"ACCEPTED"|"DECLINED"|"EXPIRED"|"CONVERTED";
export interface QuoteLineItem{type:"SERVICE"|"EXTRA"|"DISCOUNT";code?:string;name:string;description?:string;quantity:number;unitPrice:number;amount:number}
export interface QuoteRecord{_id:string;quoteNumber:string;leadId?:any;customerId?:any;serviceId:string|{_id:string;name:string};status:QuoteStatus;customer:{name:string;email:string;phone:string;address:{line1:string;line2?:string;city:string;state?:string;zip:string;country?:string}};bookingDraft:{serviceId:string;propertySize?:string;property:BookingProperty;frequency:BookingFrequency;extraCodes:string[];promoCode?:string;occurrenceCount:number};lineItems:QuoteLineItem[];pricing:{subtotal:number;discountAmount:number;taxRate:number;taxAmount:number;total:number;currency:string};estimatedDurationMinutes:number;requiredStaff:number;terms:string[];notes?:string;expiresAt:string;sentAt?:string;viewedAt?:string;acceptedAt?:string;declinedAt?:string;convertedBookingReference?:string;createdAt:string;}
export interface CreateQuoteInput{leadId?:string;customerId?:string;serviceId:string;customer:QuoteRecord["customer"];bookingDraft:{propertySize?:string;property:BookingProperty;frequency:BookingFrequency;extraCodes:string[];promoCode?:string;occurrenceCount:number};discount?:{type:"PERCENT"|"FIXED";value:number;label?:string};terms:string[];notes?:string;expiresInDays:number}
export interface PublicQuoteConversion{date:string;timeSlot:string;paymentOption:PaymentOption}

export type InvoiceStatus="DRAFT"|"OPEN"|"PARTIALLY_PAID"|"PAID"|"PARTIALLY_REFUNDED"|"REFUNDED"|"VOID";
export interface InvoiceRecord{_id:string;invoiceNumber:string;bookingId:any;jobId?:string;customerId?:any;recurrenceGroupId?:string;status:InvoiceStatus;customer:{name:string;email:string;phone?:string;address?:string};items:Array<{type:string;name:string;description?:string;quantity:number;unitPrice:number;amount:number}>;subtotal:number;discountAmount:number;taxAmount:number;total:number;amountPaid:number;amountRefunded:number;amountDue:number;currency:string;issuedAt:string;dueAt:string;paidAt?:string;notes?:string;sentAt?:string;stripeHostedInvoiceUrl?:string;}
export interface PaymentRecord{_id:string;type:"PAYMENT"|"REFUND";purpose:"DEPOSIT"|"INVOICE"|"SUBSCRIPTION"|"MANUAL"|"REFUND";provider:"STRIPE"|"MANUAL";status:"PENDING"|"SUCCEEDED"|"FAILED";amount:number;currency:string;invoiceId?:any;bookingId?:any;customerId?:any;paymentIntentId?:string;receiptUrl?:string;processedAt?:string;createdAt:string;}
export interface FinanceSummary{outstandingInvoices:number;paidRevenue:number;averageBookingValue:number;invoiceCount:number;aging:Array<{label:string;amount:number}>;}
export interface RecurringBilling{_id:string;customerId?:any;recurrenceGroupId:string;serviceName:string;amount:number;currency:string;interval:"week"|"month";intervalCount:number;status:string;stripeSubscriptionId?:string;maxPayments?:number;paymentsProcessed?:number;createdAt:string;}
export interface Paged<T>{data:T[];meta?:{page:number;limit:number;total:number;totalPages:number}}
