import type { Metadata } from "next";
import Link from "next/link";
import { BadgeCheck, CalendarClock, HeartHandshake, Sparkles } from "lucide-react";
import { SiteLayout } from "@/src/Layouts/SiteLayout";
import { getPublicWebsiteServer } from "@/src/lib/websiteServer";
import { PublicPageHero } from "@/src/components/Public/PublicPageHero";
import { CareerApplicationForm } from "@/src/components/Public/CareerApplicationForm";
export const metadata: Metadata = { title: "Careers", description: "Explore cleaning and field-team opportunities with BIO Cleaning." };
const benefits=[[CalendarClock,"Clear schedules","Know the work, service scope and customer instructions before arrival."],[BadgeCheck,"Quality standards","Checklists and field tools make the definition of done visible."],[HeartHandshake,"Respectful operations","A calm, professional workflow for customers and field teams."],[Sparkles,"Room to grow","Develop service skills and progress into crew-lead or operations roles."]] as const;
export default async function Page(){ const website=await getPublicWebsiteServer(); const email=website?.content.contact.email; return <SiteLayout website={website || undefined}><PublicPageHero eyebrow="Careers" title="Do detail-focused work with a team that values the process." description="We look for dependable, respectful people who take pride in leaving a space genuinely back in order." actions={<Link href={email?`mailto:${email}?subject=BIO Cleaning career inquiry`:"/contact"} className="btn-primary">Apply / ask about openings</Link>}/><section className="py-20"><div className="container-page grid gap-4 md:grid-cols-2">{benefits.map(([Icon,title,copy])=><article key={title} className="surface p-6"><Icon className="h-5 w-5 text-brand-green"/><h2 className="mt-4 text-xl font-extrabold text-brand-dark">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></section><section className="border-t border-border bg-brand-cream/40 py-20"><div className="container-page"><div className="mx-auto mb-8 max-w-2xl text-center"><span className="editorial-kicker">Apply online</span><h2 className="mt-3 text-3xl font-extrabold text-brand-dark">Join the field team</h2><p className="mt-2 text-sm text-muted-foreground">Applications enter the CRM so the operations team can follow up consistently.</p></div><CareerApplicationForm/></div></section></SiteLayout>; }
