import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { SiteLayout } from "@/src/Layouts/SiteLayout";
import { getPublicWebsiteServer } from "@/src/lib/websiteServer";
import { cleaningResources } from "@/src/content/resources";
const bodies: Record<string,string[]> = {
  "prepare-for-professional-cleaning": ["Confirm how the team will enter the property and make sure any alarm, gate or concierge instructions are current.","Clear the surfaces you want cleaned deeply enough that the cleaner can reach them. You do not need to pre-clean; simply remove personal clutter that would slow access.","Secure pets according to their comfort level and add any sensitivities or access notes to your customer profile.","List the two or three areas that matter most. A clear priority list helps the field team use the booked time intentionally."],
  "deep-clean-vs-regular-clean": ["Regular cleaning is designed to maintain a space that is already under control. It works best as a recurring rhythm for kitchens, bathrooms, dusting, floors and the agreed maintenance scope.","Deep cleaning is a reset. It normally allows more time for build-up, edges, detail zones and areas that do not need attention during every visit.","Choose a deep clean when it has been a long time since professional service, before starting recurring visits, after a busy season, or when the home needs a broader reset."],
  "healthy-office-cleaning-routine": ["Start with the areas people touch most often: entrances, shared kitchens, restrooms, meeting rooms and common desks.","Set the cleaning cadence around occupancy rather than a fixed assumption. A lightly used office may need fewer full cleans but still needs reliable high-touch and restroom attention.","Schedule disruptive work such as detailed floor care outside peak collaboration hours, then use a consistent maintenance scope during the normal week."],
};
export function generateStaticParams(){ return cleaningResources.map(({slug})=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const item=cleaningResources.find(x=>x.slug===slug); return item?{title:item.title,description:item.excerpt}:{}; }
export default async function Page({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const item=cleaningResources.find(x=>x.slug===slug); if(!item){ return notFound(); } const website=await getPublicWebsiteServer(); return <SiteLayout website={website || undefined}><article className="py-20"><div className="container-page max-w-3xl"><Link href="/resources" className="text-sm font-extrabold text-brand-green">← All resources</Link><p className="mt-10 text-xs font-extrabold uppercase tracking-[.14em] text-brand-green">{item.readTime} read</p><h1 className="mt-3 text-5xl font-extrabold tracking-[-.05em] text-brand-dark">{item.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{item.excerpt}</p><div className="mt-10 space-y-6 border-t border-border pt-8">{(bodies[slug]||[]).map((paragraph,i)=><p key={i} className="text-base leading-8 text-foreground/75">{paragraph}</p>)}</div><div className="mt-12 rounded-2xl bg-brand-dark p-7 text-white"><h2 className="text-2xl font-extrabold">Want a plan for your space?</h2><p className="mt-2 text-white/60">Use the live booking engine for standard work or request a custom estimate.</p><div className="mt-5 flex gap-3"><Link href="/book" className="btn-primary">Book online</Link><Link href="/quote" className="btn-secondary border-white/15 bg-white/5 text-white">Get a quote</Link></div></div></div></article></SiteLayout>; }
