import type { BookingDraft } from "./types";
import { StepHeading } from "./ServiceStep";

export function DetailsStep({ data, onChange }: { data: BookingDraft["customerDetails"]; onChange: (data: BookingDraft["customerDetails"]) => void }) {
  const address = data.address;
  return <div><StepHeading eyebrow="Step 6" title="Your contact and service address" description="We use these details for confirmation, arrival instructions, and secure booking management." /><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><input className="field-control" autoComplete="name" value={data.name} onChange={(event) => onChange({ ...data, name: event.target.value })} /></Field><Field label="Phone"><input className="field-control" autoComplete="tel" value={data.phone} onChange={(event) => onChange({ ...data, phone: event.target.value })} /></Field><div className="sm:col-span-2"><Field label="Email"><input className="field-control" type="email" autoComplete="email" value={data.email} onChange={(event) => onChange({ ...data, email: event.target.value })} /></Field></div><div className="sm:col-span-2"><Field label="Address"><input className="field-control" autoComplete="street-address" value={address.line1} onChange={(event) => onChange({ ...data, address: { ...address, line1: event.target.value } })} /></Field></div><div className="sm:col-span-2"><Field label="Apartment, suite, unit (optional)"><input className="field-control" value={address.line2 || ""} onChange={(event) => onChange({ ...data, address: { ...address, line2: event.target.value } })} /></Field></div><Field label="City"><input className="field-control" autoComplete="address-level2" value={address.city} onChange={(event) => onChange({ ...data, address: { ...address, city: event.target.value } })} /></Field><Field label="ZIP code"><input className="field-control" autoComplete="postal-code" value={address.zip} onChange={(event) => onChange({ ...data, address: { ...address, zip: event.target.value } })} /></Field></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="field-label">{label}</span>{children}</label>; }
