"use client";
import { useMemo, useState } from "react";
import { BarChart3, DollarSign, RefreshCcw, Star, TrendingUp, UsersRound, WalletCards } from "lucide-react";
import { useGetReportsQuery } from "@/src/redux/features/reporting/reportingApi";
import { ErrorState, LoadingState } from "@/src/components/ui/feedback";
const money=(n:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
const pct=(n:number)=>`${Number(n||0).toFixed(1)}%`;
function Bar({value,max}:{value:number;max:number}){ return <div className="h-2 overflow-hidden rounded-full bg-brand-cream"><div className="h-full rounded-full bg-brand-green" style={{width:`${Math.max(2,Math.min(100,max?value/max*100:0))}%`}}/></div>; }
export default function ReportsPage(){
  const now=new Date(); const monthAgo=new Date(now.getTime()-29*86400000);
  const [from,setFrom]=useState(monthAgo.toISOString().slice(0,10)); const [to,setTo]=useState(now.toISOString().slice(0,10));
  const params=useMemo(()=>({from:`${from}T00:00:00.000Z`,to:`${to}T23:59:59.999Z`}),[from,to]);
  const {data,isLoading,isError,refetch}=useGetReportsQuery(params); if(isLoading&&!data)return <LoadingState label="Building operational report…"/>; if(isError||!data)return <ErrorState title="Reports are unavailable" description="Try the report again." action={<button className="btn-secondary" onClick={()=>refetch()}>Retry</button>}/>;
  const s=data.summary; const maxSource=Math.max(1,...data.leadsBySource.map(x=>x.count)); const maxRevenue=Math.max(1,...data.revenueTrend.map(x=>Math.max(0,x.revenue)));
  const kpis=[["Net revenue",money(s.revenue),DollarSign],["Recurring revenue",money(s.recurringRevenue),RefreshCcw],["Unpaid invoices",money(s.unpaidInvoices),WalletCards],["Average order",money(s.averageOrderValue),TrendingUp],["Lead conversion",pct(s.leadConversionRate),UsersRound],["Quote acceptance",pct(s.quoteAcceptanceRate),BarChart3],["Cleaner utilization",pct(s.cleanerUtilization),UsersRound],["Review score",`${s.reviewScore.toFixed(2)} / 5`,Star]] as const;
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><span className="editorial-kicker">Business intelligence</span><h2 className="admin-page-heading mt-3 text-brand-dark">Reports that connect sales, operations and cash.</h2><p className="mt-2 text-sm text-muted-foreground">Metrics are derived from CRM, bookings, jobs, invoices, payments and reviews—not dashboard counters.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-bold text-muted-foreground">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="form-input mt-1 block"/></label><label className="text-xs font-bold text-muted-foreground">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="form-input mt-1 block"/></label></div></div>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label,value,Icon])=><article key={label} className="surface p-5"><Icon className="h-5 w-5 text-brand-green"/><p className="mt-5 text-xs font-extrabold uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-extrabold tracking-[-.04em] text-brand-dark">{value}</p></article>)}</section>
  <div className="grid gap-6 xl:grid-cols-2"><section className="surface p-6"><h3 className="text-lg font-extrabold text-brand-dark">Leads by source</h3><div className="mt-5 space-y-4">{data.leadsBySource.length?data.leadsBySource.map(row=><div key={row.source}><div className="mb-1.5 flex justify-between text-sm"><span className="font-bold text-brand-dark">{String(row.source||"Unknown").replaceAll("_"," ")}</span><span className="text-muted-foreground">{row.count} · {money(row.value)}</span></div><Bar value={row.count} max={maxSource}/></div>):<p className="text-sm text-muted-foreground">No lead activity in this range.</p>}</div></section>
  <section className="surface p-6"><h3 className="text-lg font-extrabold text-brand-dark">Revenue trend</h3><div className="mt-5 flex h-48 items-end gap-1.5 overflow-x-auto">{data.revenueTrend.length?data.revenueTrend.map(row=><div key={row.date} className="group flex min-w-3 flex-1 flex-col justify-end" title={`${row.date}: ${money(row.revenue)}`}><div className="rounded-t bg-brand-green transition group-hover:bg-brand-dark" style={{height:`${Math.max(3,(Math.max(0,row.revenue)/maxRevenue)*100)}%`}}/></div>):<p className="self-center text-sm text-muted-foreground">No successful payments in this range.</p>}</div></section></div>
  <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="table-shell overflow-x-auto"><table className="data-table min-w-[720px]"><thead><tr><th>Service</th><th>Bookings</th><th>Completed</th><th>Cancelled</th><th>Completion</th><th>Booked value</th></tr></thead><tbody>{data.servicePerformance.map(row=><tr key={row.serviceId||row.service}><td className="font-bold text-brand-dark">{row.service}</td><td>{row.bookings}</td><td>{row.completed}</td><td>{row.cancelled}</td><td>{pct(row.completionRate)}</td><td>{money(row.bookedValue)}</td></tr>)}</tbody></table></section><section className="surface p-6"><h3 className="text-lg font-extrabold text-brand-dark">Conversion & retention</h3><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Booking completion</dt><dd className="font-extrabold text-brand-dark">{pct(s.bookingCompletionRate)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Cancellation rate</dt><dd className="font-extrabold text-brand-dark">{pct(s.cancellationRate)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Customer retention</dt><dd className="font-extrabold text-brand-dark">{pct(s.customerRetentionRate)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Review satisfaction</dt><dd className="font-extrabold text-brand-dark">{pct(data.reviews.satisfactionRate)}</dd></div></dl></section></div></div>;
}
