import type { WebsiteHomepageSection, WebsiteServiceArea, WebsiteSnapshot } from "@/src/redux/features/website/types";
import { ArrowRight, Clock, MapPin, Navigation } from "lucide-react";
import Link from "next/link";
import { publicSlug } from "@/src/lib/publicSlug";

export default function ServiceNetwork({ areas, contact, section }: { areas?: WebsiteServiceArea[]; contact?: WebsiteSnapshot["contact"]; section?: WebsiteHomepageSection }) {
  const zones = (areas || []).filter((area) => area.visible).sort((a, b) => a.order - b.order);
  const displayZones = zones.length ? zones : [{ id: "ny", name: "New York", description: "", visible: true, order: 1 }, { id: "nj", name: "New Jersey", description: "", visible: true, order: 2 }, { id: "bos", name: "Greater Boston", description: "", visible: true, order: 3 }];
  return <section className="bg-brand-cream py-24"><div className="container-page"><div className="mb-12 text-center"><span className="pill" data-reveal>— {section?.eyebrow || "Coverage"} —</span><h2 className="mt-3 text-4xl font-display text-brand-dark md:text-5xl" data-reveal>{section?.title || "Our service network"}</h2><p className="mx-auto mt-3 max-w-xl text-muted-foreground" data-reveal>{section?.subtitle || contact?.serviceAreaSummary || "Professional cleaning across the communities we serve."}</p></div>
    <div className="grid items-stretch gap-5 lg:grid-cols-[1fr_360px]" data-reveal><div className="relative min-h-[420px] overflow-hidden rounded-2xl border border-border bg-white shadow-xl">{contact?.mapEmbedUrl ? <iframe title="Service area map" src={contact.mapEmbedUrl} className="h-[485px] w-full" loading="lazy" /> : <div className="grid h-[485px] place-items-center bg-[radial-gradient(circle_at_30%_20%,rgba(181,236,86,.28),transparent_34%),linear-gradient(135deg,#f3f6ea,#e5efe6)] p-8 text-center"><div><MapPin className="mx-auto h-10 w-10 text-brand-green" /><h3 className="mt-4 text-2xl font-bold text-brand-dark">Service area map</h3><p className="mt-2 max-w-md text-sm text-muted-foreground">Add a map embed URL in Website → Contact & areas to display an interactive map here.</p></div></div>}<div className="absolute left-6 top-6 max-w-xs rounded-2xl bg-white p-4 shadow-2xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-brand-green"><MapPin className="h-3.5 w-3.5" /> BIO Cleaning</div><div className="mt-1 text-lg font-display text-brand-dark">{contact?.address || "Local cleaning teams"}</div><div className="mt-1 text-xs text-muted-foreground">{contact?.hours || "Online booking available"}</div><Link href="/contact" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-brand-green">Contact us <ArrowRight className="h-3 w-3" /></Link></div></div>
    <div className="flex flex-col justify-between rounded-2xl bg-brand-dark p-7 text-white"><div><span className="pill bg-brand-lime text-brand-dark"><Navigation className="h-3.5 w-3.5" /> Active routes</span><h3 className="mt-5 text-3xl font-display">Coverage managed from one live service-area list</h3><p className="mt-3 text-sm text-white/65">Availability still comes from the scheduling engine; these are the public areas your team wants customers to see.</p></div><div className="mt-8 space-y-3">{displayZones.slice(0, 8).map((zone) => <Link key={zone.id} href={`/service-areas/${publicSlug(zone.name)}`} className="flex items-center justify-between rounded-2xl bg-white/8 p-4 transition hover:bg-white/12"><span>{zone.name}</span><span className="flex items-center gap-1 text-sm text-brand-lime"><Clock className="h-3.5 w-3.5" /> Explore</span></Link>)}</div></div></div>
  </div></section>;
}
