"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, Home, Sparkles } from "lucide-react";
import type { CleaningService } from "@/src/redux/features/services/types";
import type { WebsiteHomepageSection } from "@/src/redux/features/website/types";

export default function ServiceFinder({ services, section }: { services: CleaningService[]; section?: WebsiteHomepageSection }) {
  const [space, setSpace] = useState<"HOME"|"OFFICE">("HOME");
  const [intensity, setIntensity] = useState<"regular"|"deep">("regular");
  const suggested = useMemo(() => services.find((service) => `${service.name} ${service.tags?.join(" ")}`.toLowerCase().includes(intensity === "deep" ? "deep" : space === "OFFICE" ? "commercial" : "residential")) || services[0], [services, space, intensity]);
  return <section className="bg-white py-20"><div className="container-page"><div className="grid gap-8 rounded-2xl border border-border bg-brand-cream/45 p-6 shadow-card lg:grid-cols-[.8fr_1.2fr] lg:p-10"><div><span className="editorial-kicker">{section?.eyebrow || "Service finder"}</span><h2 className="mt-4 text-4xl font-extrabold tracking-[-.045em] text-brand-dark">{section?.title || "Tell us the space. We’ll point you to the right clean."}</h2><p className="mt-4 text-muted-foreground">{section?.subtitle || "A fast starting point before the full booking configurator calculates your exact scope and availability."}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="surface p-5"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-muted-foreground">Space</p><div className="mt-3 grid grid-cols-2 gap-2">{([["HOME",Home,"Home"],["OFFICE",Building2,"Office"]] as const).map(([value,Icon,label])=><button key={value} onClick={()=>setSpace(value)} className={`rounded-xl border p-4 text-left ${space===value?"border-brand-green bg-brand-green/5":"border-border bg-white"}`}><Icon className="h-5 w-5 text-brand-green"/><span className="mt-2 block text-sm font-bold text-brand-dark">{label}</span></button>)}</div></div><div className="surface p-5"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-muted-foreground">Need</p><div className="mt-3 grid grid-cols-2 gap-2">{(["regular","deep"] as const).map((value)=><button key={value} onClick={()=>setIntensity(value)} className={`rounded-xl border p-4 text-left ${intensity===value?"border-brand-green bg-brand-green/5":"border-border bg-white"}`}><Sparkles className="h-5 w-5 text-brand-green"/><span className="mt-2 block text-sm font-bold capitalize text-brand-dark">{value}</span></button>)}</div></div><div className="sm:col-span-2 flex flex-col gap-4 rounded-xl bg-brand-dark p-5 text-white sm:flex-row sm:items-center"><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.12em] text-brand-lime">Suggested starting point</p><p className="mt-1 text-xl font-extrabold">{suggested?.name || "Custom cleaning plan"}</p></div><Link href={suggested ? `/book?serviceId=${encodeURIComponent(suggested._id)}` : "/quote"} className="btn-primary">Continue <ArrowRight className="h-4 w-4"/></Link></div></div></div></div></section>;
}
