"use client";

import Link from "next/link";
import { AlertTriangle, CheckCircle2, Clock3, MapPin, Navigation, Sparkles } from "lucide-react";
import { useGetMyFieldOverviewQuery } from "@/src/redux/features/fieldOps/fieldOpsApi";
import { LoadingState, EmptyState } from "@/src/components/ui/feedback";

export default function StaffDashboard(){
  const {data,isLoading,isError}=useGetMyFieldOverviewQuery();
  if(isLoading)return <LoadingState label="Loading today’s jobs…"/>; if(isError||!data)return <EmptyState title="Could not load field work" description="Please refresh or contact your dispatcher."/>;
  return <div className="space-y-5"><section className="rounded-2xl bg-brand-dark p-5 text-white shadow-elevated sm:p-6"><span className="editorial-kicker border-white/10 bg-white/8 text-brand-lime">Today · {data.date}</span><h1 className="mt-3 text-3xl font-extrabold tracking-[-.045em]">Ready for a clean day, {data.staff.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-white/60">Times are shown in {data.timezone}. Open a job before arrival to review access notes and service scope.</p><div className="mt-5 grid grid-cols-4 gap-2">{[["Jobs",data.summary.total],["Ready",data.summary.scheduled],["Active",data.summary.active],["Done",data.summary.completed]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-white/10 bg-white/7 p-3"><div className="text-xl font-extrabold text-brand-lime">{value}</div><div className="text-[9px] font-bold uppercase tracking-[.12em] text-white/45">{label}</div></div>)}</div></section>
    <section><div className="flex items-center justify-between"><div><span className="text-[10px] font-extrabold uppercase tracking-[.14em] text-brand-green">Assigned route</span><h2 className="mt-1 text-xl font-extrabold text-brand-dark">Today’s visits</h2></div><Sparkles className="h-5 w-5 text-brand-green"/></div><div className="mt-4 space-y-3">{data.jobs.map((job)=><Link key={job._id} href={`/staff/jobs/${job._id}`} className="block rounded-2xl border border-border bg-white p-4 shadow-sm transition hover:border-brand-green/30 hover:shadow-card"><div className="flex items-start gap-3"><span className={`mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-xl ${job.status==="COMPLETED"?"bg-brand-green/10 text-brand-green":job.status==="ISSUE"?"bg-destructive/10 text-destructive":"bg-brand-lime text-brand-dark"}`}>{job.status==="COMPLETED"?<CheckCircle2 className="h-4 w-4"/>:job.status==="ISSUE"?<AlertTriangle className="h-4 w-4"/>:<Clock3 className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div className="truncate font-extrabold text-brand-dark">{job.customerName}</div><span className="status-badge border-border bg-brand-cream text-[9px] text-brand-dark">{job.status.replace("_"," ")}</span></div><p className="mt-1 text-xs font-semibold text-brand-green">{new Intl.DateTimeFormat("en-US",{timeZone:data.timezone,hour:"numeric",minute:"2-digit"}).format(new Date(job.scheduledStart))} — {new Intl.DateTimeFormat("en-US",{timeZone:data.timezone,hour:"numeric",minute:"2-digit"}).format(new Date(job.scheduledEnd))}</p><p className="mt-2 flex items-start gap-1.5 text-xs leading-5 text-muted-foreground"><MapPin className="mt-.5 h-3.5 w-3.5 shrink-0"/>{job.address.line1}, {job.address.city} {job.address.zip}</p><div className="mt-3 flex items-center justify-between"><span className="text-[10px] font-bold text-muted-foreground">{job.checklist.filter(item=>item.completed).length}/{job.checklist.length} tasks complete</span><span className="inline-flex items-center gap-1 text-[10px] font-extrabold text-brand-green">Open job <Navigation className="h-3 w-3"/></span></div></div></div></Link>)}</div>{!data.jobs.length?<div className="mt-4"><EmptyState title="No jobs assigned today" description="You’re clear for now. New assignments will appear here after dispatch updates them."/></div>:null}</section>
  </div>;
}
