"use client";

import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AlertTriangle, Camera, Check, CheckCircle2, Clock3, ExternalLink, Loader2, MapPin, MessageSquareText, Navigation, Pause, Play, Upload } from "lucide-react";
import { useUploadFileMutation } from "@/src/redux/features/assets/assetsApi";
import { useAddJobNoteMutation, useAddJobPhotoMutation, useGetFieldJobQuery, useReportJobIssueMutation, useResolveJobIssueMutation, useUpdateJobChecklistMutation, useUpdateJobStatusMutation } from "@/src/redux/features/fieldOps/fieldOpsApi";
import type { JobStatus } from "@/src/redux/features/fieldOps/types";
import { LoadingState } from "@/src/components/ui/feedback";

function errorMessage(error:any){return error?.data?.message||error?.data?.error||"Could not update the job.";}

export default function StaffJobPage(){
  const params=useParams<{id:string}>();const {data:job,isLoading}=useGetFieldJobQuery(params.id);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [updateStatus,{isLoading:statusLoading}]=useUpdateJobStatusMutation();const [updateChecklist]=useUpdateJobChecklistMutation();const [uploadFile,{isLoading:uploading}]=useUploadFileMutation();const [addPhoto]=useAddJobPhotoMutation();const [addNote]=useAddJobNoteMutation();const [reportIssue]=useReportJobIssueMutation();const [resolveIssue]=useResolveJobIssueMutation();
  const progress=useMemo(()=>job?.checklist.length?Math.round(job.checklist.filter(item=>item.completed).length/job.checklist.length*100):100,[job]);
  if(isLoading||!job)return <LoadingState label="Opening job details…"/>;
  const setStatus=async(status:JobStatus)=>{setError("");try{await updateStatus({id:job._id,status}).unwrap();}catch(err){setError(errorMessage(err));}};
  const uploadEvidence=async(event:ChangeEvent<HTMLInputElement>,type:"BEFORE"|"AFTER"|"ISSUE")=>{const file=event.target.files?.[0];if(!file)return;setError("");try{const form=new FormData();form.append("file",file);const uploaded:any=await uploadFile(form).unwrap();const url=uploaded?.data?.url||uploaded?.url;if(!url)throw new Error("Upload did not return a URL");await addPhoto({id:job._id,type,url}).unwrap();event.target.value="";}catch(err){setError(errorMessage(err));}};
  const submitNote=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const text=String(form.get("text")||"");if(!text.trim())return;try{await addNote({id:job._id,text}).unwrap();event.currentTarget.reset();}catch(err){setError(errorMessage(err));}};
  const submitIssue=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await reportIssue({id:job._id,title:String(form.get("title")),description:String(form.get("description")),severity:String(form.get("severity")) as any}).unwrap();event.currentTarget.reset();}catch(err){setError(errorMessage(err));}};
  const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${job.address.line1}, ${job.address.city} ${job.address.zip}`)}`;
  const timezone=job.businessTimezone || "America/New_York";
  const startLabel=new Intl.DateTimeFormat("en-US",{timeZone:timezone,month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(job.scheduledStart));
  const endLabel=new Intl.DateTimeFormat("en-US",{timeZone:timezone,hour:"numeric",minute:"2-digit"}).format(new Date(job.scheduledEnd));
  const active=!['COMPLETED','CANCELLED'].includes(job.status);
  return <div className="space-y-5">
    <section className="rounded-2xl bg-brand-dark p-5 text-white shadow-elevated"><div className="flex items-start justify-between gap-3"><div><span className="editorial-kicker border-white/10 bg-white/8 text-brand-lime">{job.jobNumber}</span><h1 className="mt-3 text-2xl font-extrabold tracking-[-.04em]">{job.customerName}</h1><p className="mt-1 text-xs text-white/55">{typeof job.serviceId==="string"?"Cleaning service":job.serviceId?.name||"Cleaning service"}</p></div><span className={`status-badge ${job.status==="ISSUE"?"border-red-300/20 bg-red-300/10 text-red-200":"border-white/10 bg-white/8 text-brand-lime"}`}>{job.status.replace("_"," ")}</span></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><a href={maps} target="_blank" rel="noreferrer" className="flex items-start gap-2 rounded-xl border border-white/10 bg-white/7 p-3 text-xs leading-5 text-white/75"><MapPin className="mt-.5 h-4 w-4 shrink-0 text-brand-lime"/><span>{job.address.line1}{job.address.line2?`, ${job.address.line2}`:""}, {job.address.city} {job.address.zip}</span><ExternalLink className="ml-auto h-3.5 w-3.5 shrink-0"/></a><div className="rounded-xl border border-white/10 bg-white/7 p-3 text-xs text-white/75"><Clock3 className="mr-2 inline h-4 w-4 text-brand-lime"/>{startLabel} — {endLabel}</div></div></section>
    {error?<div className="feedback-panel border-destructive/20 bg-destructive/5 text-destructive" role="alert">{error}</div>:null}{message?<div className="feedback-panel border-brand-green/20 bg-brand-green/5 text-brand-green">{message}</div>:null}

    {active?<section className="surface p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{job.status==="SCHEDULED"?<button disabled={statusLoading} onClick={()=>setStatus("EN_ROUTE")} className="btn-secondary"><Navigation className="h-4 w-4"/>On the way</button>:null}{["SCHEDULED","EN_ROUTE","PAUSED","ISSUE"].includes(job.status)?<button disabled={statusLoading} onClick={()=>setStatus("IN_PROGRESS")} className="btn-primary"><Play className="h-4 w-4"/>Start / resume</button>:null}{job.status==="IN_PROGRESS"?<button disabled={statusLoading} onClick={()=>setStatus("PAUSED")} className="btn-secondary"><Pause className="h-4 w-4"/>Pause</button>:null}{["IN_PROGRESS","ISSUE"].includes(job.status)?<button disabled={statusLoading} onClick={()=>setStatus("COMPLETED")} className="btn-secondary"><CheckCircle2 className="h-4 w-4"/>Complete job</button>:null}</div></section>:null}

    <section className="surface p-5"><div className="flex items-center justify-between gap-3"><div><span className="text-[10px] font-extrabold uppercase tracking-[.14em] text-brand-green">Service checklist</span><h2 className="mt-1 text-xl font-extrabold text-brand-dark">Complete the promised scope</h2></div><span className="text-sm font-extrabold text-brand-green">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-brand-cream"><div className="h-full bg-brand-green transition-all" style={{width:`${progress}%`}}/></div><div className="mt-4 space-y-2">{job.checklist.map(item=><label key={item.key} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${item.completed?"border-brand-green/20 bg-brand-green/5":"border-border bg-white"}`}><input type="checkbox" className="mt-1 h-4 w-4 accent-brand-green" checked={item.completed} onChange={(e)=>updateChecklist({id:job._id,key:item.key,completed:e.target.checked})}/><span className={`text-sm font-semibold ${item.completed?"text-brand-green line-through":"text-brand-dark"}`}>{item.label}</span>{item.completed?<Check className="ml-auto h-4 w-4 text-brand-green"/>:null}</label>)}</div></section>

    {job.customerInstructions?<section className="surface p-5"><span className="text-[10px] font-extrabold uppercase tracking-[.14em] text-brand-green">Customer & access instructions</span><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-brand-dark">{job.customerInstructions}</p></section>:null}

    <section className="surface p-5"><div className="flex items-center gap-2"><Camera className="h-4 w-4 text-brand-green"/><h2 className="font-extrabold text-brand-dark">Before & after evidence</h2></div><div className="mt-4 grid grid-cols-2 gap-3"><UploadButton label="Before photo" uploading={uploading} onChange={(e)=>uploadEvidence(e,"BEFORE")}/><UploadButton label="After photo" uploading={uploading} onChange={(e)=>uploadEvidence(e,"AFTER")}/></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{job.photos.map(photo=><figure key={photo.key} className="overflow-hidden rounded-xl border border-border bg-brand-cream"><img src={photo.url} alt={`${photo.type.toLowerCase()} cleaning evidence`} className="aspect-square w-full object-cover"/><figcaption className="p-2 text-[10px] font-extrabold text-brand-dark">{photo.type}</figcaption></figure>)}</div></section>

    <section className="surface p-5"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-600"/><h2 className="font-extrabold text-brand-dark">Issues</h2></div><div className="mt-4 space-y-3">{job.issues.map(issue=><article key={issue.key} className={`rounded-xl border p-3 ${issue.status==="OPEN"?"border-amber-200 bg-amber-50":"border-brand-green/20 bg-brand-green/5"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-extrabold text-brand-dark">{issue.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{issue.description}</p></div><span className="status-badge border-border bg-white text-[9px]">{issue.severity}</span></div>{issue.status==="OPEN"?<button onClick={async()=>{const resolution=window.prompt("Resolution note");if(resolution)await resolveIssue({id:job._id,issueKey:issue.key,resolution})}} className="btn-secondary mt-3 px-3 py-2">Resolve</button>:<p className="mt-2 text-[11px] font-bold text-brand-green">Resolved · {issue.resolution}</p>}</article>)}</div>{active?<form onSubmit={submitIssue} className="mt-4 grid gap-2 rounded-xl border border-border p-3"><input name="title" required className="field-control" placeholder="Issue title"/><textarea name="description" required className="field-control min-h-20" placeholder="What happened?"/><div className="flex gap-2"><select name="severity" defaultValue="MEDIUM" className="field-control"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select><button className="btn-secondary shrink-0"><AlertTriangle className="h-4 w-4"/>Report</button></div></form>:null}</section>

    <section className="surface p-5"><div className="flex items-center gap-2"><MessageSquareText className="h-4 w-4 text-brand-green"/><h2 className="font-extrabold text-brand-dark">Internal notes</h2></div><div className="mt-4 space-y-2">{job.internalNotes.map((note,index)=><div key={index} className="rounded-xl bg-brand-cream p-3 text-xs leading-5 text-brand-dark">{note.text}<div className="mt-1 text-[10px] text-muted-foreground">{new Date(note.createdAt).toLocaleString()}</div></div>)}</div><form onSubmit={submitNote} className="mt-4 flex gap-2"><input name="text" className="field-control" placeholder="Add a note for the team"/><button className="btn-secondary shrink-0">Add note</button></form></section>
  </div>;
}

function UploadButton({label,uploading,onChange}:{label:string;uploading:boolean;onChange:(event:ChangeEvent<HTMLInputElement>)=>void}){return <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-brand-green/35 bg-brand-green/5 p-4 text-xs font-extrabold text-brand-green hover:bg-brand-green/10"><input type="file" accept="image/jpeg,image/png" className="sr-only" disabled={uploading} onChange={onChange}/>{uploading?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}{label}</label>}
