"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { FileText, Loader2, Mail, Plus, X } from "lucide-react";
import { useCreateQuoteMutation, useGetQuotesQuery, useSendQuoteMutation } from "@/src/redux/features/finance/financeApi";
import { useGetAllServicesAdminQuery } from "@/src/redux/features/services/servicesApi";
import { useGetCustomerQuery, useGetLeadQuery } from "@/src/redux/features/crm/crmApi";
import { EmptyState, ErrorState, TableSkeleton } from "@/src/components/ui/feedback";
import { FieldLabel, SelectInput, TextArea, TextInput } from "@/src/components/ui/form-field";

const statusClass=(s:string)=>s==="CONVERTED"||s==="ACCEPTED"?"status-success":s==="DECLINED"||s==="EXPIRED"?"status-danger":"status-neutral";
export default function QuotesPage(){
 const [context,setContext]=useState({leadId:"",customerId:""}); const {leadId,customerId}=context; const prefilled=useRef(false);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setContext({leadId:params.get("leadId")||"",customerId:params.get("customerId")||""});},[]);
 const [open,setOpen]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const {data,isLoading,isError,refetch}=useGetQuotesQuery({limit:100}); const {data:serviceResp}=useGetAllServicesAdminQuery({}); const services:any[]=(serviceResp as any)?.data||(serviceResp as any)||[];
 const leadQuery=useGetLeadQuery(leadId,{skip:!leadId}); const customerQuery=useGetCustomerQuery(customerId,{skip:!customerId});
 const [createQuote,createState]=useCreateQuoteMutation(); const [sendQuote,sendState]=useSendQuoteMutation();
 const [form,setForm]=useState<any>({serviceId:"",name:"",email:"",phone:"",line1:"",city:"",zip:"",propertyType:"HOME",bedrooms:2,bathrooms:1,frequency:"ONE_TIME",extraCodes:[],discountType:"FIXED",discountValue:"",discountLabel:"",terms:"Payment is due according to the accepted estimate.\nSchedule changes remain subject to live availability.",notes:"",expiresInDays:14});
 const selected=useMemo(()=>services.find((s:any)=>s._id===form.serviceId),[services,form.serviceId]);
 useEffect(()=>{
   if(prefilled.current)return;
   const lead=leadQuery.data?.data?.lead; const customer=customerQuery.data?.data?.customer;
   if(leadId&&lead){
     const requestedServiceId=typeof lead.requestedServiceId==="object"?lead.requestedServiceId?._id:lead.requestedServiceId;
     const linked=typeof lead.customerId==="object"?lead.customerId:undefined; const address=linked?.addresses?.find((a:any)=>a.isPrimary)||linked?.addresses?.[0];
     setForm((current:any)=>({...current,serviceId:requestedServiceId||current.serviceId,name:lead.name||current.name,email:lead.email||current.email,phone:lead.phone||current.phone,line1:address?.line1||current.line1,city:address?.city||current.city,zip:address?.zip||current.zip,propertyType:address?.propertyType||current.propertyType,notes:lead.message||lead.notes||current.notes}));
     prefilled.current=true;setOpen(true);
   } else if(customerId&&customer){
     const address=customer.addresses?.find((a:any)=>a.isPrimary)||customer.addresses?.[0];
     setForm((current:any)=>({...current,name:customer.name||current.name,email:customer.email||current.email,phone:customer.phone||current.phone,line1:address?.line1||current.line1,city:address?.city||current.city,zip:address?.zip||current.zip,propertyType:address?.propertyType||current.propertyType}));
     prefilled.current=true;setOpen(true);
   }
 },[leadId,customerId,leadQuery.data,customerQuery.data]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");try{await createQuote({leadId:leadId||undefined,customerId:customerId||undefined,serviceId:form.serviceId,customer:{name:form.name,email:form.email,phone:form.phone,address:{line1:form.line1,city:form.city,zip:form.zip}},bookingDraft:{property:{propertyType:form.propertyType,bedrooms:Number(form.bedrooms||0),bathrooms:Number(form.bathrooms||0)},frequency:form.frequency,extraCodes:form.extraCodes,occurrenceCount:1},discount:Number(form.discountValue)>0?{type:form.discountType,value:Number(form.discountValue),label:form.discountLabel||undefined}:undefined,terms:String(form.terms).split("\n").map((x:string)=>x.trim()).filter(Boolean),notes:form.notes||undefined,expiresInDays:Number(form.expiresInDays||14)} as any).unwrap();setOpen(false);setNotice("Estimate created. Send it when you are ready.");}catch(err:any){setError(err?.data?.message||"Could not create estimate.");}};
 const send=async(id:string)=>{setError("");try{await sendQuote(id).unwrap();setNotice("Estimate emailed with a secure acceptance link.");}catch(err:any){setError(err?.data?.message||"Could not send estimate.");}};
 if(isError)return <ErrorState title="Estimates are unavailable" action={<button className="btn-secondary" onClick={()=>refetch()}>Retry</button>}/>;
 return <div className="space-y-6"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="editorial-kicker">Sales documents</span><h2 className="admin-page-heading mt-2 text-brand-dark">Quotes & estimates</h2><p className="mt-2 text-sm text-muted-foreground">Send professional, expiring estimates that customers can accept and convert into a live booking.</p></div><button className="btn-primary" onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>New estimate</button></section>{notice?<div className="rounded-xl border border-brand-green/20 bg-brand-green/5 px-4 py-3 text-sm font-semibold text-brand-green">{notice}</div>:null}{error?<div className="rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm font-semibold text-destructive">{error}</div>:null}
 {isLoading?<TableSkeleton rows={6} columns={6}/>:data?.data?.length?<div className="table-shell overflow-x-auto"><table className="data-table min-w-[860px]"><thead><tr><th>Estimate</th><th>Customer</th><th>Service</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.data.map(q=><tr key={q._id}><td><p className="font-mono text-xs font-bold text-brand-dark">{q.quoteNumber}</p><p className="mt-1 text-[11px] text-muted-foreground">Expires {new Date(q.expiresAt).toLocaleDateString()}</p></td><td><p className="font-bold text-brand-dark">{q.customer.name}</p><p className="text-xs text-muted-foreground">{q.customer.email}</p></td><td>{typeof q.serviceId==="object"?q.serviceId.name:"Cleaning service"}</td><td className="font-extrabold text-brand-dark">{q.pricing.currency} {q.pricing.total.toFixed(2)}</td><td><span className={`status-badge ${statusClass(q.status)}`}>{q.status.replaceAll("_"," ")}</span></td><td><button disabled={sendState.isLoading||["CONVERTED","DECLINED","EXPIRED"].includes(q.status)} onClick={()=>send(q._id)} className="btn-secondary !h-8 !px-3"><Mail className="h-3.5 w-3.5"/>Send</button></td></tr>)}</tbody></table></div>:<EmptyState icon={FileText} title="No estimates yet" description="Create an estimate for a lead or customer and send it for electronic acceptance." action={<button className="btn-primary" onClick={()=>setOpen(true)}>Create estimate</button>}/>} 
 {open?<div className="fixed inset-0 z-[80] grid place-items-center bg-brand-dark/45 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><p className="editorial-kicker">New estimate</p><h3 className="mt-2 text-2xl font-extrabold text-brand-dark">Build a customer-ready quote</h3></div><button className="grid h-9 w-9 place-items-center rounded-lg hover:bg-muted" onClick={()=>setOpen(false)}><X className="h-4 w-4"/></button></div><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><FieldLabel>Service</FieldLabel><SelectInput required value={form.serviceId} onChange={e=>setForm({...form,serviceId:e.target.value,extraCodes:[]})}><option value="">Choose service</option>{services.filter((s:any)=>s.isActive!==false).map((s:any)=><option key={s._id} value={s._id}>{s.name} · from ${s.basePrice}</option>)}</SelectInput></label><label><FieldLabel>Customer name</FieldLabel><TextInput required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><FieldLabel>Email</FieldLabel><TextInput required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><FieldLabel>Phone</FieldLabel><TextInput required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><FieldLabel>Address</FieldLabel><TextInput required value={form.line1} onChange={e=>setForm({...form,line1:e.target.value})}/></label><label><FieldLabel>City</FieldLabel><TextInput required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label><FieldLabel>ZIP / postal</FieldLabel><TextInput required value={form.zip} onChange={e=>setForm({...form,zip:e.target.value})}/></label><label><FieldLabel>Property type</FieldLabel><SelectInput value={form.propertyType} onChange={e=>setForm({...form,propertyType:e.target.value})}><option value="HOME">Home</option><option value="OFFICE">Office</option><option value="OTHER">Other</option></SelectInput></label><label><FieldLabel>Frequency</FieldLabel><SelectInput value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="ONE_TIME">One time</option><option value="WEEKLY">Weekly</option><option value="BI_WEEKLY">Every 2 weeks</option><option value="MONTHLY">Monthly</option></SelectInput></label>{form.propertyType==="HOME"?<><label><FieldLabel>Bedrooms</FieldLabel><TextInput type="number" min="0" value={form.bedrooms} onChange={e=>setForm({...form,bedrooms:e.target.value})}/></label><label><FieldLabel>Bathrooms</FieldLabel><TextInput type="number" min="0" step="0.5" value={form.bathrooms} onChange={e=>setForm({...form,bathrooms:e.target.value})}/></label></>:null}
 {selected?.pricing?.extras?.filter((x:any)=>x.isActive!==false).length?<div className="sm:col-span-2"><FieldLabel>Add-ons</FieldLabel><div className="mt-2 grid gap-2 sm:grid-cols-2">{selected.pricing.extras.filter((x:any)=>x.isActive!==false).map((x:any)=><label key={x.code} className="flex items-center gap-3 rounded-xl border border-border p-3 text-sm"><input type="checkbox" checked={form.extraCodes.includes(x.code)} onChange={e=>setForm({...form,extraCodes:e.target.checked?[...form.extraCodes,x.code]:form.extraCodes.filter((c:string)=>c!==x.code)})}/><span className="flex-1 font-semibold text-brand-dark">{x.name}</span><span className="text-muted-foreground">+${x.price}</span></label>)}</div></div>:null}
 <div className="sm:col-span-2 rounded-xl border border-border bg-brand-cream/35 p-4"><FieldLabel>Optional estimate discount</FieldLabel><div className="mt-2 grid gap-2 sm:grid-cols-[150px_150px_1fr]"><SelectInput value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})}><option value="FIXED">Fixed amount</option><option value="PERCENT">Percentage</option></SelectInput><TextInput type="number" min="0" max={form.discountType==="PERCENT"?100:undefined} step="0.01" placeholder={form.discountType==="PERCENT"?"10":"25.00"} value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/><TextInput maxLength={120} placeholder="Label, e.g. New customer" value={form.discountLabel} onChange={e=>setForm({...form,discountLabel:e.target.value})}/></div></div>
 <label className="sm:col-span-2"><FieldLabel>Terms (one per line)</FieldLabel><TextArea value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})}/></label><label className="sm:col-span-2"><FieldLabel>Optional notes</FieldLabel><TextArea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label><FieldLabel>Expires in days</FieldLabel><TextInput type="number" min="1" max="90" value={form.expiresInDays} onChange={e=>setForm({...form,expiresInDays:e.target.value})}/></label><div className="sm:col-span-2 flex justify-end gap-2 border-t border-border pt-4"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" disabled={createState.isLoading}>{createState.isLoading?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Create estimate</button></div></form></div></div>:null}
 </div>;
}
